version: '3.7'

services:
  server:
    build: .
    ports:
    - 3001:3001
    depends_on:
    - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ehr
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
        - default

volumes:
  mongodb_data_container: